
import './globals.css'


export const metadata = {
  title: 'Toughdata',
  description: 'Generated by create next app and Developer MD. Faysal[mdfaysal.freelancer@gmail.com]',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-[#FCFCFC]'>{children}</body>
    </html>
  )
}
